services:
    ma27_api_key_authentication.annotation_driver:
        class: Ma27\ApiKeyAuthenticationBundle\Service\Mapping\Driver\AnnotationDriver
        public: false
        arguments:
            - "@annotation_reader"
            - "%ma27_api_key_authentication.model_name%"

    ma27_api_key_authentication.class_metadata_factory:
        class: Ma27\ApiKeyAuthenticationBundle\Service\Mapping\ClassMetadataFactory
        public: false
        arguments:
            - "@ma27_api_key_authentication.annotation_driver" # TODO refactor, should be configured in the extension
            - "@filesystem"
            - "%ma27_api_key_authentication.metadata_cache_enabled%"
            - ~
            - "%ma27_api_key_authentication.model_name%"

    ma27_api_key_authentication.class_metadata:
        class: Ma27\ApiKeyAuthenticationBundle\Service\Mapping\ClassMetadata
        factory:
            - "@ma27_api_key_authentication.class_metadata_factory"
            - "createMetadataObject"
