services:
    ma27_api_key_authentication.auth_handler:
        class: Ma27\ApiKeyAuthenticationBundle\Model\Login\ApiToken\ApiKeyAuthorizationHandler
        arguments:
            - @=service(parameter('ma27.auth.object_manager))
            - @ma27_api_key_authentication.password.strategy
            - @ma27_api_key_authentication.key_factory
            - @event_dispatcher
            - %ma27_api_key_authentication.model_name%
            - %ma27_api_key_authentication.property.password%
            - %ma27_api_key_authentication.property.username%
            - %ma27_api_key_authentication.property.email%
