services:
    ma27.auth.service.auth_handler:
        class: Ma27\ApiKeyAuthenticationBundle\Model\Login\ApiToken\ApiKeyAuthorizationHandler
        arguments:
            - @=service(parameter('ma27.auth.object_manager))
            - @ma27.auth.password.strategy
            - @ma27.auth.service.key_factory
            - @event_dispatcher
            - %ma27.auth.model_name%
            - %ma27.auth.property.password%
            - %ma27.auth.property.username%
            - %ma27.auth.property.email%
