services:
    ma27_api_key_authentication.auth_handler:
        class: Ma27\ApiKeyAuthenticationBundle\Model\Login\ApiToken\ApiKeyAuthenticationHandler
        arguments:
            - "@=service(parameter('ma27_api_key_authentication.object_manager'))"
            - "@ma27_api_key_authentication.password.strategy"
            - "@ma27_api_key_authentication.key_factory"
            - "@event_dispatcher"
            - "%ma27_api_key_authentication.model_name%"
            - "@ma27_api_key_authentication.class_metadata"
    ma27_api_key_authentication.response_listener:
        class: Ma27\ApiKeyAuthenticationBundle\EventListener\ResponseCreationListener
        arguments:
            - "@translator"
            - "@ma27_api_key_authentication.class_metadata"
        tags:
            - { name: kernel.event_subscriber }
