services:
    ma27_api_key_authentication.key_factory:
        class: Ma27\ApiKeyAuthenticationBundle\Model\Key\KeyFactory
        arguments:
            - ~
            - %ma27_api_key_authentication.model_name%
            - %ma27_api_key_authentication.property.apiKey%
            - %ma27_api_key_authentication.property.apiKeyLength%
        public: false
