services:
    ma27.auth.service.key_factory:
        class: Ma27\ApiKeyAuthenticationBundle\Model\Key\KeyFactory
        arguments:
            - ~
            - %ma27.auth.model_name%
            - %ma27.auth.property.apiKey%
        public: false
