services:
    ma27.auth.service.security.authenticator:
        class: Ma27\ApiKeyAuthenticationBundle\Security\ApiKeyAuthenticator
        arguments:
            - ~
            - @event_dispatcher
            - %ma27.auth.model_name%
            - %ma27.auth.property.apiKey%
