services:
    ma27_api_key_authentication.cleanup_command:
        class: Ma27\ApiKeyAuthenticationBundle\Command\SessionCleanupCommand
        tags:
            - { name: console.command }
        arguments:
            - ~
            - @ma27_api_key_authentication.auth_handler
            - @event_dispatcher
            - %ma27_api_key_authentication.model_name%
            - %ma27_api_key_authentication.last_activation_parameter%
            - ~
