services:
    ma27.auth.service.cleanup_command:
        class: Ma27\ApiKeyAuthenticationBundle\Command\SessionCleanupCommand
        tags:
            - { name: console.command }
        arguments:
            - ~
            - @ma27.auth.service.auth_handler
            - @event_dispatcher
            - %ma27.auth.model_name%
            - %ma27.auth.last_activation_parameter%
            -
