before_commands:
    - 'composer install'

filter:
    excluded_paths:
        - Tests/

tools:
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['.']
    php_mess_detector: true
    php_analyzer: true
    php_pdepend: true
    external_code_coverage: true
    php_loc:
        enabled: true
        excluded_dirs: [Tests]
    php_cpd:
        enabled: true
        excluded_dirs: [Tests]
