language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.6
      env: SF_VERSION=2.7.*

install:
  - if [ "$SF_VERSION" != "" ]; then composer require "symfony/symfony:${SF_VERSION}" --no-update; fi;
  - composer install

script:
  - vendor/bin/phpunit
