language: php
php:
  - 7.1

sudo: false

matrix:
  include:
    - php: 7.1
      env: SF_VERSION=2.8

install:
  - if [ "$SF_VERSION" != "" ]; then composer require "symfony/symfony:${SF_VERSION}" --no-update; fi;
  - composer install
  - mysql -e "CREATE DATABASE IF NOT EXISTS symfony_functional"
  - echo "use mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user = 'root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - php ./Tests/Resources/app/console.php doctrine:schema:create

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
